name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        API_KEY: ${{ secrets.API_KEY }}
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }} 

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'pnpm'
        - name: Install dependencies
          run: pnpm install
        - name: Start server and test
          run: pnpm run test
